### ISSUE TITLE
Multi-line padded text

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-awesomeness#142]
Multi-line padded text:

```css
/*
<span><span>Some text</span></span>
*/

span {
    padding: 10px;
    display: inline; /* If not already. */
    background: rgba(255, 255, 255, .9);
    -webkit-box-decoration-break: clone;
    -moz-box-decoration-break: clone;
    -ms-box-decoration-break: clone;
    -o-box-decoration-break: clone;
    box-decoration-break: clone;
}
span > span {
    position: relative; /* Prevents background overlap on wrapped lines. */
}
```
