### ISSUE TITLE
Make sure .scroll is latest code

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-awesomeness#2]
I took the current one from Picard theme.

**Comment by mhulse** [comment]
Also, img stuff may not be needed. Here's an update:

```css
.scroll {
	overflow-y: auto;
	-webkit-overflow-scrolling: touch;
}
.scroll > * {
	margin-top: 0;
	margin-bottom: 0;
	-webkit-transform: translateZ(0);
}
```

Also, I just noticed that this is similar to bootstrap 3's `responsive-table` class.
