### ISSUE TITLE
Faux border using background-image linear-gradient

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-awesomeness#216]
```css
.header {
    background-image:linear-gradient(90deg,transparent 16px,#fff 0,#fff calc(100% - 16px),transparent calc(100% - 16px));
    background-position: 0 100%;
    background-repeat: no-repeat;
    background-size: 100% 1px
}
```
