### ISSUE TITLE
.h1 - .h6

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-awesomeness#4]
Add those, and link to StackOverflow comment on why they are good/used.

**Comment by mhulse** [comment]
SCSS example:

```css
h1, h2, h3, h4, h5, h6 {
	
	letter-spacing: .02em;
	word-spacing: .12em;
	// For really long words (might consider removing):
	word-wrap: break-word;
	overflow-wrap: break-word;
	margin: 25px 0;
	padding: 0;
	
	& + & { margin-top: -20px; }
	
	a {
		
		&,
		&:visited { color: $color2; }
		.no-touch &:visited:hover,
		&:focus,
		.no-touch &:focus:hover,
		.no-touch &:hover,
		&:active {
			color: saturate(lighten($color2, 20%), 20%);
			text-decoration: none;
		}
		
	}
	
}

.sh1, .sh2, .sh3, .sh4, .sh5, .sh6 { font-weight: normal; }

h1, .h1, .sh1 {
	font-size: 26px;
	line-height: 28px;
}

h2, .h2, .sh2 {
	font-size: 24px;
	line-height: 26px;
}

h3, .h3, .sh3 {
	font-size: 22px;
	line-height: 24px;
}

h4, .h4, .sh4 {
	font-size: 20px;
	line-height: 22px;
}

h5, .h5, .sh5 {
	font-size: 18px;
	line-height: 20px;
}

h6, .h6, .sh6 {
	font-size: 16px;
	line-height: 18px;
}

h1:empty { display: none; }
```

**Comment by mhulse** [comment]
CSS:

```css
h1, h2, h3, h4, h5, h6 {
	line-height: 1.2;
	letter-spacing: .02em;
	word-spacing: .12em;
	margin: 2.5rem 0;
	padding: 0;
}
h1 + h1, h1 + h2, h1 + h3, h1 + h4, h1 + h5, h1 + h6,
h2 + h1, h2 + h2, h2 + h3, h2 + h4, h2 + h5, h2 + h6,
h3 + h1, h3 + h2, h3 + h3, h3 + h4, h3 + h5, h3 + h6,
h4 + h1, h4 + h2, h4 + h3, h4 + h4, h4 + h5, h4 + h6,
h5 + h1, h5 + h2, h5 + h3, h5 + h4, h5 + h5, h5 + h6,
h6 + h1, h6 + h2, h6 + h3, h6 + h4, h6 + h5, h6 + h6 { margin-top: -2rem; }

.sh1, .sh2, .sh3, .sh4, .sh5, .sh6 { font-weight: normal; }

h1, .h1, .sh1 {
	font-size: 2.6rem;
}

h2, .h2, .sh2 {
	font-size: 2.4rem;
}

h3, .h3, .sh3 {
	font-size: 2.2rem;
}

h4, .h4, .sh4 {
	font-size: 2rem;
}

h5, .h5, .sh5 {
	font-size: 1.8rem;
}

h6, .h6, .sh6 {
	font-size: 1.6rem;
}

h1:empty { display: none; }
```

**Comment by mhulse** [comment]
This also works:

```scss
h1, h2, h3, h4, h5, h6 {
	
	a {
		
		&,
		&:visited,
		&:visited:hover,
		&:focus,
		&:focus:hover,
		&:hover,
		&:active { color: $brand-success; }
		
	}
	
	& + & {
		font-weight: 400;
		margin-top: -.325em;
	}
	
}
```

No need for .sh1 classes as the assumption is if a heading follows a heading, then it's a subhead with a normal weight.

**Comment by mhulse** [comment]
CSS version:

```css
h1, h2, h3, h4, h5, h6 {
	font-weight: bold;
	line-height: 1.2;
	letter-spacing: .02em;
	word-spacing: .12em;
	margin: 2.5rem 0;
	padding: 0;
}
h1 + h1, h1 + h2, h1 + h3, h1 + h4, h1 + h5, h1 + h6,
h2 + h1, h2 + h2, h2 + h3, h2 + h4, h2 + h5, h2 + h6,
h3 + h1, h3 + h2, h3 + h3, h3 + h4, h3 + h5, h3 + h6,
h4 + h1, h4 + h2, h4 + h3, h4 + h4, h4 + h5, h4 + h6,
h5 + h1, h5 + h2, h5 + h3, h5 + h4, h5 + h5, h5 + h6,
h6 + h1, h6 + h2, h6 + h3, h6 + h4, h6 + h5, h6 + h6 {
	font-weight: normal;
	margin-top: -2rem;
}
h1, .h1 { font-size: 2.6rem; }
h2, .h2 { font-size: 2.4rem; }
h3, .h3 { font-size: 2.2rem; }
h4, .h4 { font-size: 2rem; }
h5, .h5 { font-size: 1.8rem; }
h6, .h6 { font-size: 1.6rem; }
h1:empty { display: none; }
```
