### ISSUE TITLE
Add precedence note

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-awesomeness#7]
```css
/*
** Suggested (approximate) precedence of commonly used CSS properties:
	
	selector {
		font: value;
		font-*: value;
		color: value;
		text-*: value;
		letter-spacing: value;
		word-spacing: value;
		line-height: value;
		list-*: value;
		background: value;
		background-*: value;
		border: value;
		border-*: value;
		margin: value;
		margin-*: value;
		padding: value;
		padding-*: value;
		width: value;
		height: value;
		float: value;
		display: value;
		clear: value;
		position: value;
		left: value;
		right: value;
		top: value;
		bottom: value;
		overflow: value;
		z-index: value;
	}
	
** 
*/
```

The above is from here: http://assets.registerguard.com/v3.5/css/master.css

Also, I move that to this doc more recently:

https://github.com/mhulse/gh-boiler/blob/master/CONTRIBUTING.md#cascading-style-sheets-css
